version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.4
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run specs with rspec-atoms
          command: circleci run testsuite "rspec-atoms specs"
      - store_test_results:
          path: tmp/test-results
      - run:
          name: Build gem
          command: bundle exec rake build

workflows:
  test:
    jobs:
      - test
